name: crdt

packages:
  - packages/**

repository: https://github.com/MattiaPispisa/crdt

sdkPath: .fvm/flutter_sdk

command:
  bootstrap:
    hooks:
      post: dart run scripts/flutter_example_bs.dart
  publish:
    hooks:
      pre: melos run format && melos run analyze && melos run test && melos run test_flutter && melos run test_chrome && melos run devtools_build
      post: melos run benchmark

scripts:
  docs_bs:
    name: "Docs bootstrap"
    description: "Documentation bootstrap"
    run: dart run scripts/docs_bs.dart
  docs_build:
    name: "Docs build"
    description: "Build the documentation site"
    run: dart run scripts/docs_build.dart
  benchmark:
    name: Benchmark
    description: Run the benchmarks
    run: cd packages/crdt_lf && ./benchmark/run.sh

  test:
    name: Test
    description: Run the Dart tests
    run: dart test
    exec:
      concurrency: 1
    packageFilters:
      flutter: false
      dirExists: test

  test_flutter:
    name: Test (Flutter)
    description: Run the Flutter tests
    run: flutter test
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: test

  test_chrome:
    name: Test (Chrome)
    description: Run the tests on Chrome (web)
    run: dart test -p chrome
    exec:
      concurrency: 1
    packageFilters:
      flutter: false
      dirExists: test
  analyze:
    name: Analyze
    description: Analyze the code
    run: dart analyze --fatal-infos --fatal-warnings lib test
    exec:
      concurrency: 1

  devtools_build:
    name: Devtools Build
    description: Build the devtools extension
    run: cd ./packages/crdt_lf_devtools_extension && dart run devtools_extensions build_and_copy --source=. --dest=../crdt_lf/extension/devtools && dart run devtools_extensions validate --package=../crdt_lf

  fix_apply:
    name: Fix Apply
    description: Apply the fixes
    run: dart fix --apply
    exec:
      concurrency: 1

  format:
    name: Format
    description: Format the code
    run: dart format --line-length 80 --set-exit-if-changed lib test
    exec:
      concurrency: 1
