name: crdt

packages:
  - packages/**

repository: https://github.com/invertase/melos

sdkPath: .fvm/flutter_sdk

scripts:
  test:
    name: Test
    description: Run the tests
    run: dart test
    exec:
      concurrency: 1
