name: crdt

packages:
  - packages/**

repository: https://github.com/MattiaPispisa/crdt

sdkPath: .fvm/flutter_sdk

command:
  publish:
    hooks:
      pre: melos run format && melos run analyze && melos run test && melos run devtools_build 
      post: melos run benchmark

scripts:
  benchmark:
    name: Benchmark
    description: Run the benchmarks
    run: cd packages/crdt_lf && ./benchmark/run.sh

  test:
    name: Test
    description: Run the tests
    run: dart test
    exec:
      concurrency: 1
  analyze:
    name: Analyze
    description: Analyze the code
    run: dart analyze --fatal-infos --fatal-warnings lib test
    exec:
      concurrency: 1

  devtools_build:
    name: Devtools Build
    description: Build the devtools extension
    run: cd ./packages/crdt_lf_devtools_extension && dart run devtools_extensions build_and_copy --source=. --dest=../crdt_lf/extension/devtools && dart run devtools_extensions validate --package=../crdt_lf

  fix_apply:
    name: Fix Apply
    description: Apply the fixes
    run: dart fix --apply
    exec:
      concurrency: 1

  format:
    name: Format
    description: Format the code
    run: dart format --line-length 80 --set-exit-if-changed lib test
    exec:
      concurrency: 1