name: crdt

packages:
  - packages/**

repository: https://github.com/MattiaPispisa/crdt

sdkPath: .fvm/flutter_sdk

command:
  publish:
    hooks:
      pre: melos run analyze && melos run test && melos run devtools_build

scripts:
  test:
    name: Test
    description: Run the tests
    run: dart test
    exec:
      concurrency: 1
  analyze:
    name: Analyze
    description: Analyze the code
    run: dart analyze --fatal-infos --fatal-warnings
    exec:
      concurrency: 1

  devtools_build:
    name: Devtools Build
    description: Build the devtools extension
    run: cd ./packages/crdt_lf_devtools_extension && dart run devtools_extensions build_and_copy --source=. --dest=../crdt_lf/extension/devtools && dart run devtools_extensions validate --package=../crdt_lf
