name: hlc_dart
description: A Hybrid Logical Clock implementation in Dart, based on the paper "Logical Physical Clocks and Consistent Snapshots in Globally Distributed Databases".
homepage: https://mattiapispisa.github.io/
repository: https://github.com/MattiaPispisa/crdt/tree/main/packages/hlc
topics: [local-first, hlc, logical-clocks, distributed-systems]

version: 0.3.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  test: ^1.24.0
