name: hlc_dart
description: Hybrid Logical Clock implementation
homepage: https://mattiapispisa.github.io/
repository: https://github.com/MattiaPispisa/crdt/packages/hlc
topics: [local-first, hlc, logical-clocks, distributed-systems]

version: 0.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  test: ^1.24.0
