name: crdt_lf_hive
description: Hive adapters for CRDT LF library objects, providing persistence for Change and Snapshot objects.
homepage: https://mattiapispisa.github.io/
repository: https://github.com/MattiaPispisa/crdt/tree/main/packages/crdt_lf_hive
topics: [local-first, crdt, hive, persistence, dart]
publish_to: none

version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  crdt_lf:
    path: ../crdt_lf
  hive: ^2.2.3
  hlc_dart: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.12
  hive_generator: ^2.0.1
  lints: ^4.0.0
  test: ^1.24.0 