name: crdt_lf_hive
description: Hive adapters for CRDT LF library objects, providing persistence for Change and Snapshot objects.
homepage: https://mattiapispisa.github.io/
repository: https://github.com/MattiaPispisa/crdt/tree/main/packages/crdt_lf_hive
topics: [local-first, crdt, hive, persistence, dart]

version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  crdt_lf: ^0.7.0
  hive: ^2.0.0
  hlc_dart: ^0.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
