name: crdt_socket_sync_client_example
description: "Flutter client example for crdt_socket_sync."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3

  hlc_dart: ^1.0.0
  crdt_lf: ^1.0.0
  crdt_lf_flutter:
    path: ../../crdt_lf_flutter
  crdt_socket_sync: ">=0.2.0 <1.0.0"
  provider: ^6.1.4
  en_logger: ^1.2.0
  shared_examples_infrastructure:
    path: ../../shared_examples_infrastructure

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  test: 

flutter:

  uses-material-design: true