name: plugin bug
description: Create a new bug issue for a plugin
title: "[plugin] "
labels: ["p:1","bug"]
projects: ["MattiaPispisa/1"]
assignees:
  - MattiaPispisa

body:
  - type: dropdown
    id: plugin
    attributes:
      label: What plugin has the bug?
      multiple: false
      options:
        - hive
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Call method ...
        2. Instantiate class ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using?
      placeholder: e.g. 1.0.0
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: More information
      description: Any other information that might be useful, also screenshots.
      placeholder: Additional context, screenshots, logs, etc.