name: crdt_lf_sqlite
description: sqlite3 storage adapter for CRDT LF library objects, providing persistence for Change and Snapshot objects.
homepage: https://mattiapispisa.github.io/
repository: https://github.com/MattiaPispisa/crdt/tree/main/packages/crdt_lf_sqlite
topics: [crdt, local-first, sqlite, persistence, dart]

version: 0.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crdt_lf: "^3.0.0"
  hlc_dart: ^1.0.0
  sqlite3: ^3.0.0

dev_dependencies:
  test: ^1.24.0
