name: crdt_lf
description: Conflict-free replicated data type (CRDT) - Local-first implementation provided in dart
homepage: https://mattiapispisa.github.io/
repository: https://github.com/MattiaPispisa/crdt/tree/main/packages/crdt_lf
topics: [crdt, local-first, fugue, hlc]

version: 0.7.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  crypto: ^3.0.0
  hlc_dart: ^0.3.0

dev_dependencies:
  test: ^1.24.0
