name: Monorepo CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  hlc:
    uses: ./.github/workflows/dart_package.yaml
    with:
      working_directory: ./packages/hlc
      min_coverage: 90
      package_name: hlc_dart
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  crdt_lf:
    uses: ./.github/workflows/dart_package.yaml
    with:
      working_directory: ./packages/crdt_lf
      min_coverage: 90
      package_name: crdt_lf
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  crdt_lf_hive:
    uses: ./.github/workflows/dart_package.yaml
    with:
      working_directory: ./packages/crdt_lf_hive
      min_coverage: 90
      package_name: crdt_lf_hive
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  crdt_lf_sqlite:
    uses: ./.github/workflows/dart_package.yaml
    with:
      working_directory: ./packages/crdt_lf_sqlite
      min_coverage: 90
      package_name: crdt_lf_sqlite
      install_sqlite: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  crdt_lf_drift:
    uses: ./.github/workflows/dart_package.yaml
    with:
      working_directory: ./packages/crdt_lf_drift
      min_coverage: 90
      package_name: crdt_lf_drift
      install_sqlite: true
      coverage_exclude: "**/*.g.dart"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  crdt_socket_sync:
    uses: ./.github/workflows/dart_package.yaml
    with:
      working_directory: ./packages/crdt_socket_sync
      min_coverage: 70
      package_name: crdt_socket_sync
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  crdt_lf_flutter:
    uses: ./.github/workflows/flutter_package.yaml
    with:
      working_directory: ./packages/crdt_lf_flutter
      min_coverage: 80
      package_name: crdt_lf_flutter
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
